set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @catppuccin_window_tabs_enabled on # or off to disable window_tabs
set -g @catppuccin_date_time "%Y-%m-%d %H:%M"

set -g @plugin 'alexwforsythe/tmux-which-key'

# set -g @catppuccin_user "on"
# set -g @catppuccin_host "on"

# set -g @plugin 'dracula/tmux'

set -g @continuum 'on'

unbind C-b
unbind C-Space
set -g prefix C-Space
bind -n C-Space send-prefix

# Mouse mode
set -g mouse on

# split window replacement
unbind %
unbind '"'
bind v split-window -v -c "#{pane_current_path}"
bind g split-window -h -c "#{pane_current_path}"

# vim-like screen focus
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# set -g status-keys emacs
# setw -g mode-keys emacs

set-option -g default-shell /opt/homebrew/bin/fish
# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

run '~/.tmux/plugins/tpm/tpm'
