# theme = "kanagawa"
theme = "dracula"
# theme = "kanagawa-dragon"

[editor]
line-number = "relative"
bufferline = "multiple"
soft-wrap.enable = true
cursor-shape.insert = "underline"
whitespace.render.tab = "all"

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "╎", "┆", "┊", "⸽"
skip-levels = 1
